// import slugify from '../utils/slugify'

export default {
  title: "Team",
  name: 'team',
  type: "document",
  fields: [
    {
      title: "Name",
      name: "name",
      description: "The name of this team member",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      name: "order",
      title: "Order",
      type: "number",
      hidden: true,
    },
    {
      title: "Job Title",
      name: "jobTitle",
      description: "The title of this team member's position. eg: 'Head of Strategy & Operations'",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: 'Department',
      name: 'department',
      type: 'reference',
      to: [{type: 'departments'}]
    },
    {
      title: 'Location',
      name: 'location',
      type: 'reference',
      to: [{type: 'locations'}]
    },
    {
      title: "Avatar",
      name: "avatar",
      description: "The image of this team member",
      type: "image",
      validation: Rule => Rule.required()
    },
    {
      title: 'Bio',
      name: 'bio',
      description: 'The short biography of this team member',
      type: 'array', 
      of: [{type: 'block'}]
    },
    // {
    //   name: 'slug',
    //   type: 'slug',
    //   title: 'Slug',
    //   description: 'This is required for page routing and can be auto-generated by pressing "generate"',
    //   options: {
    //     source: 'title',
    //     maxLength: 96,
    //     slugify: name => slugify(name)
    //   },
    //   validation: Rule => Rule.required()
    // },
    // {
    //   title: 'SEO / Share Settings',
    //   name: 'seo',
    //   type: 'seo'
    // }
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'jobTitle',
      media: 'avatar'
    }
  }
}