// import slugify from '../utils/slugify'

export default {
  title: "Team",
  name: 'team',
  type: "document",
  fields: [
    {
      title: "Name",
      name: "name",
      description: "The name of this team member",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Job Title",
      name: "jobTitle",
      description: "The title of this team member's position. eg: 'Head of Strategy & Operations'",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Avatar",
      name: "avatar",
      description: "The image of this team member",
      type: "image",
      validation: Rule => Rule.required()
    },
    {
      title: 'Bio',
      name: 'bio',
      description: 'The short biography of this team member',
      type: 'array', 
      of: [{type: 'block'}],
      validation: Rule => Rule.required()
    },
    // {
    //   name: 'slug',
    //   type: 'slug',
    //   title: 'Slug',
    //   description: 'This is required for page routing and can be auto-generated by pressing "generate"',
    //   options: {
    //     source: 'title',
    //     maxLength: 96,
    //     slugify: name => slugify(name)
    //   },
    //   validation: Rule => Rule.required()
    // },
    // {
    //   title: 'SEO / Share Settings',
    //   name: 'seo',
    //   type: 'seo'
    // }
  ]
}